Repository Onboarding Prep
openclarity/kubeclarity pull request #432
Opened 2023-05-18 19:19 UTC by lelia

These changes will help prepare this repository to onboard contributors who are new to open source, and may need extra time and guidance in order to make their first contributions. 

This will be done in concert with an audit of existing open project issues, in order to determine whether any existing issues need to be unmarked as `stale`, or labeled as `good first issue`. 

After identifying a few good issues, we can direct participants to **[/contribute](https://github.com/openclarity/kubeclarity/contribute)** to find a curated list of issues, as well as a link to the `CONTRIBUTING.md` guidelines.

## Changes

* Repository configuration settings (`.github/settings.yml`)
* Stalebot issue settings + phrasing (`.github/stalebot.yml`)

2023-05-19 07:34 UTC, sambetts-cisco requested changes

2023-05-19 07:34 UTC, sambetts-cisco commented on .github/stale.yml
> -  your contributions.
This was our wording, we preferred as developers to have reasoning and timelines for when these actions would occur.

I'm happy to move the thank you to the beginning of the statement.

2023-05-19 07:34 UTC, sambetts-cisco commented on .github/stale.yml
> +  if the issue is still relevant. Thank you!
ditto I prefer to state the reasoning here, and the reason is that its been stale for over 30 days.

2023-05-23 18:04 UTC, lelia commented
Closing in favor of https://github.com/openclarity/.github/issues/14

2023-05-23 18:04 UTC, closed without merging